#!/bin/bash

# Check root
if [ "$(id -u)" -ne 0 ]; then
        echo ""
        echo "This script requires root privileges."
        echo ""
        exit 1
fi

# Check if the correct number of arguments are provided
if [ "$#" -ne 1 ]; then
    echo ""
    echo "Usage: $0 <thingsboard> or $0 <mosquitto>"
    echo ""
    exit 1
fi

# Get the argument service name passed to the script
service=$1

case $service in
    thingsboard)

        sudo systemctl stop thingsboard.service
        sudo systemctl start mosquitto
        exit 1
        ;;

    mosquitto)

        sudo systemctl stop thingsboard.service
        sudo systemctl start mosquitto
        exit 1
        ;;

    *)

        echo "service not known, thingsboard or mosquitto only."
        exit 1
        ;;

esac