#!/usr/bin/bash

sudo rm -rf  /usr/local/bin/switch

if [[ $? -eq 0 ]]; then

    sleep 0.5

    echo "uninstall succesfully"

    sleep 1
    rm -f "/usr/local/bin/uninstall_switch"

else
    echo "run the installer first"

fi